name: Python Package Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]  # ubuntu-latest as of 2023-06 (possibly late 2022) is ubuntu-22.04
        os: [ubuntu-20.04, macos-latest, windows-latest]
        #python-version: ['3.5', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12', 'pypy2.7', 'pypy3.8']
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', 'pypy2.7', 'pypy3.8']
        exclude:
          - os: macos-latest
            python-version: '3.5'
          - os: macos-latest
            python-version: '3.7'
          - os: macos-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.6'
          - os: ubuntu-latest
            python-version: '3.5'
          - os: ubuntu-20.04
            python-version: '3.5'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: env PYTHONWARNINGS="ignore::DeprecationWarning" python -m pip install --upgrade pip
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: env PYTHONWARNINGS="ignore::DeprecationWarning" python -m pip install -r requirements.txt
      - name: install
        run: python -m pip install -e .
      - name: Run  Python tests
        run: python -m x10_any.test.tests
